/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_system_project;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author win10dell
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        setLocationRelativeTo(null);
        icon();
    }
    
    void usernameA(String username){
        lbladminusername.setText(username);
    }
     private void icon(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("244650586_432577631535911_8014217671605978899_n.png")));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlogout = new javax.swing.JButton();
        btnborrowed = new javax.swing.JButton();
        btnpending = new javax.swing.JButton();
        btnlist = new javax.swing.JButton();
        btnregbook = new javax.swing.JButton();
        lbladminusername = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Library Management System/admin_menu/");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(50, 157, 156));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnlogout.setBackground(new java.awt.Color(255, 255, 255));
        btnlogout.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnlogout.setText("Logout");
        btnlogout.setBorder(null);
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
        });
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 613, 80, 30));

        btnborrowed.setBackground(new java.awt.Color(255, 255, 255));
        btnborrowed.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnborrowed.setText("Borrowed Books");
        btnborrowed.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 152, 133), 3, true));
        btnborrowed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnborrowedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnborrowedMouseExited(evt);
            }
        });
        jPanel1.add(btnborrowed, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 360, -1));

        btnpending.setBackground(new java.awt.Color(255, 255, 255));
        btnpending.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnpending.setText("Pending Borrow Request");
        btnpending.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 152, 133), 3, true));
        btnpending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpendingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpendingMouseExited(evt);
            }
        });
        jPanel1.add(btnpending, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 360, -1));

        btnlist.setBackground(new java.awt.Color(255, 255, 255));
        btnlist.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnlist.setText("Lists of Users");
        btnlist.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 152, 133), 3, true));
        btnlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlistMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlistMouseExited(evt);
            }
        });
        jPanel1.add(btnlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 360, -1));

        btnregbook.setBackground(new java.awt.Color(255, 255, 255));
        btnregbook.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnregbook.setText("Register/Update Books");
        btnregbook.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(124, 152, 133), 3, true));
        btnregbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnregbookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnregbookMouseExited(evt);
            }
        });
        jPanel1.add(btnregbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 360, -1));

        lbladminusername.setBackground(new java.awt.Color(124, 152, 133));
        lbladminusername.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        lbladminusername.setForeground(new java.awt.Color(255, 255, 255));
        lbladminusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladminusername.setOpaque(true);
        jPanel1.add(lbladminusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 340, 30));

        jLabel3.setBackground(new java.awt.Color(124, 152, 133));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome Admin!");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 380, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Downloads\\244321751_427596305376778_6719107591455322172_n (1).png")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        jLabel2.setBackground(new java.awt.Color(125, 208, 182));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 380, 640));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Downloads\\244421648_914487879157927_5244009138292318583_n (2).png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Library Management System");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setText("Cavite State University - Naic ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Downloads\\244467596_285374813451858_4973129835230929871_n.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setBackground(new java.awt.Color(125, 208, 182));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 470, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(929, 716));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnregbookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregbookMouseEntered
       btnregbook.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_btnregbookMouseEntered

    private void btnlistMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlistMouseEntered
        btnlist.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_btnlistMouseEntered

    private void btnpendingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpendingMouseExited
         btnpending.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnpendingMouseExited

    private void btnborrowedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnborrowedMouseEntered
         btnborrowed.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_btnborrowedMouseEntered

    private void btnregbookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregbookMouseExited
         btnregbook.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnregbookMouseExited

    private void btnlistMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlistMouseExited
        btnlist.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnlistMouseExited

    private void btnpendingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpendingMouseEntered
        btnpending.setBackground(java.awt.Color.yellow);
    }//GEN-LAST:event_btnpendingMouseEntered

    private void btnborrowedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnborrowedMouseExited
        btnborrowed.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnborrowedMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int logout = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?","Logout",JOptionPane.OK_CANCEL_OPTION);
        
        if(logout==0){
        new Login().setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
        btnlogout.setBackground(java.awt.Color.red);
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
        btnlogout.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnlogoutMouseExited

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        int logout = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?","Logout",JOptionPane.OK_CANCEL_OPTION);
        
        if(logout==0){
        new Login().setVisible(true);
        dispose();}
    }//GEN-LAST:event_btnlogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnborrowed;
    private javax.swing.JButton btnlist;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnpending;
    private javax.swing.JButton btnregbook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbladminusername;
    // End of variables declaration//GEN-END:variables
}
