package library_system_project;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Regform extends javax.swing.JFrame {

    Connection connect;
    ResultSet ab;
    PreparedStatement pre;
    int id = -1;

    /**
     * Creates new form Regform
     */
    public Regform() {
        initComponents();
        icon();
        setResizable(false);
    }

    public Regform(int id) {
        this.id = id;
        initComponents();
        icon();
        setResizable(false);
        cbusertype.setEnabled(true);

        if (id > 0) {
            btnsubmit.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Desktop\\LMS Icon\\regupdate.png"));
            updateUser(id);
        }
    }

    private void updateUser(int id) {
        connect = DbConnection.getConnection();

        try {
            Statement s = connect.createStatement();

            ab = s.executeQuery("Select * from tablelms where UserID = " + id);

            while (ab.next()) {
                txtusername.setText(ab.getString("username"));
                pswdreg.setText(ab.getString("password"));
                pswdretype.setText(ab.getString("password"));
                txtnumber.setText(ab.getString("contact").replace("+63", ""));
                txtemail.setText(ab.getString("email"));
                txtfname.setText(ab.getString("firstname"));
                txtmid.setText(ab.getString("mid"));
                txtlname.setText(ab.getString("lastname"));
                txtaddress.setText(ab.getString("address"));
                cbgender.setSelectedItem(ab.getString("gender"));
                cbusertype.setSelectedItem(ab.getString("usertype"));
                ((JTextField) jDatebday.getDateEditor().getUiComponent()).setText(ab.getString("bday"));

                if (ab.getString("Status").equals("Activated")) {
                    btnclear.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Desktop\\LMS Icon\\deactivate.png"));
                } else {
                    btnclear.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Desktop\\LMS Icon\\activate.png"));
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void icon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconnn.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        pswdretype = new javax.swing.JPasswordField();
        cbusertype = new javax.swing.JComboBox<>();
        cbgender = new javax.swing.JComboBox<>();
        txtemail = new javax.swing.JTextField();
        txtnumber1 = new javax.swing.JTextField();
        txtnumber = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        pswdreg = new javax.swing.JPasswordField();
        txtmid = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtshowpas = new javax.swing.JLabel();
        txtshow = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbage = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDatebday = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Library Management System/create_account/");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(50, 157, 156));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setBackground(new java.awt.Color(255, 255, 255));
        btnback.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Desktop\\LMS Icon\\rback.png")); // NOI18N
        btnback.setOpaque(false);
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 93, 38));

        btnsubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnsubmit.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnsubmit.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Desktop\\LMS Icon\\submit.png")); // NOI18N
        btnsubmit.setOpaque(false);
        btnsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsubmitMouseExited(evt);
            }
        });
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 103, 38));

        btnclear.setBackground(new java.awt.Color(255, 255, 255));
        btnclear.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Desktop\\LMS Icon\\rclear.png")); // NOI18N
        btnclear.setOpaque(false);
        btnclear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnclearFocusGained(evt);
            }
        });
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclearMouseExited(evt);
            }
        });
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 93, 38));

        pswdretype.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pswdretype.setToolTipText("Re-enter password");
        pswdretype.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswdretypeFocusLost(evt);
            }
        });
        pswdretype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdretypeActionPerformed(evt);
            }
        });
        pswdretype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pswdretypeKeyTyped(evt);
            }
        });
        jPanel1.add(pswdretype, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 190, -1));

        cbusertype.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbusertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        cbusertype.setEnabled(false);
        cbusertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbusertypeActionPerformed(evt);
            }
        });
        jPanel1.add(cbusertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 160, -1));

        cbgender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Select gender)", "Female", "Male", "Prefer Not To Answer" }));
        jPanel1.add(cbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 140, -1));

        txtemail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtemail.setToolTipText("Enter email address");
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 160, -1));

        txtnumber1.setEditable(false);
        txtnumber1.setBackground(new java.awt.Color(255, 255, 255));
        txtnumber1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtnumber1.setText("+63");
        txtnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumber1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 40, -1));

        txtnumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtnumber.setToolTipText("Enter contact number");
        txtnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberActionPerformed(evt);
            }
        });
        txtnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumberKeyTyped(evt);
            }
        });
        jPanel1.add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 120, -1));

        txtaddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaddress.setToolTipText("Enter address");
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 330, -1));

        pswdreg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pswdreg.setToolTipText("Enter password");
        pswdreg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswdregFocusLost(evt);
            }
        });
        pswdreg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pswdregPropertyChange(evt);
            }
        });
        pswdreg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pswdregKeyTyped(evt);
            }
        });
        jPanel1.add(pswdreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 190, -1));

        txtmid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtmid.setToolTipText("Enter middle initial");
        txtmid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmidKeyTyped(evt);
            }
        });
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 60, -1));

        txtlname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtlname.setToolTipText("Enter last name");
        jPanel1.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 160, -1));

        txtfname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtfname.setToolTipText("Enter first name");
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 160, -1));

        txtusername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtusername.setToolTipText("Enter username");
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 190, -1));

        txtshowpas.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtshowpas.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(txtshowpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 160, 20));

        txtshow.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtshow.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(txtshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 160, 20));

        jLabel22.setBackground(new java.awt.Color(16, 119, 124));
        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Contact and User Type");
        jLabel22.setOpaque(true);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 180, 20));

        jLabel21.setBackground(new java.awt.Color(16, 119, 124));
        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Personal Info");
        jLabel21.setOpaque(true);
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 160, 20));

        jLabel20.setBackground(new java.awt.Color(16, 119, 124));
        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Account Details");
        jLabel20.setOpaque(true);
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 140, 20));

        lbage.setBackground(new java.awt.Color(255, 255, 255));
        lbage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        lbage.setOpaque(true);
        jPanel1.add(lbage, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 90, 20));

        jLabel15.setBackground(new java.awt.Color(16, 119, 124));
        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Age:");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 50, 20));

        jDatebday.setBackground(new java.awt.Color(255, 255, 255));
        jDatebday.setToolTipText("Select birth date");
        jDatebday.setDateFormatString("yyyy/MM/dd");
        jDatebday.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jDatebday.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDatebdayPropertyChange(evt);
            }
        });
        jPanel1.add(jDatebday, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 150, 20));

        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 119, 124), 2, true));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 300, 160));

        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 119, 124), 2, true));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 770, 140));

        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(16, 119, 124), 2, true));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 260, 160));

        jLabel14.setBackground(new java.awt.Color(16, 119, 124));
        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Birthday:");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 100, 20));

        jLabel12.setBackground(new java.awt.Color(16, 119, 124));
        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("User Type:");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 90, 20));

        jLabel11.setBackground(new java.awt.Color(16, 119, 124));
        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Email:");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 90, 20));

        jLabel10.setBackground(new java.awt.Color(16, 119, 124));
        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Contact #:");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 90, 20));

        jLabel9.setBackground(new java.awt.Color(16, 119, 124));
        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Address:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 100, 20));

        jLabel8.setBackground(new java.awt.Color(16, 119, 124));
        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gender:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 100, 20));

        jLabel7.setBackground(new java.awt.Color(16, 119, 124));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Middle Initial:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 100, 20));

        jLabel6.setBackground(new java.awt.Color(16, 119, 124));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Last Name:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 100, 20));

        jLabel5.setBackground(new java.awt.Color(16, 119, 124));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("First Name:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, 20));

        jLabel17.setBackground(new java.awt.Color(16, 119, 124));
        jLabel17.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Desktop\\LMS Icon\\userpass.png")); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 50, 40));

        jLabel4.setBackground(new java.awt.Color(16, 119, 124));
        jLabel4.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Desktop\\LMS Icon\\userpass.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 50, 40));

        jLabel3.setBackground(new java.awt.Color(16, 119, 124));
        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Desktop\\LMS Icon\\userlogin.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 50, 40));

        jLabel1.setBackground(new java.awt.Color(207, 244, 210));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Desktop\\LMS Icon\\reg.png")); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(886, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        if (id > 0) {
            String icon = btnclear.getIcon().toString();
            String status = "";
            if (icon.equals("C:\\Users\\win10dell\\Desktop\\LMS Icon\\activate.png")) {
                status = "Activated";
            } else {
                status = "Deactivated";
            }
            try {
                int confirm = JOptionPane.showConfirmDialog(null, "Are you sure to " + status.replace("d", "") + " account?", status.replace("d", ""), JOptionPane.OK_CANCEL_OPTION);

                if (confirm == 0) {
                    connect = DbConnection.getConnection();
                    pre = connect.prepareStatement("UPDATE tablelms SET status = '" + status + "' WHERE UserID = " + id);
                    pre.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Account " + status, "Success", JOptionPane.PLAIN_MESSAGE);
                    this.dispose();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            txtusername.setText("");
            pswdreg.setText("");
            txtfname.setText("");
            txtlname.setText("");
            txtmid.setText("");
            cbgender.setSelectedIndex(0);
            txtaddress.setText("");
            txtnumber.setText("");
            txtemail.setText("");
            cbusertype.setSelectedIndex(0);
            jDatebday.setCalendar(null);
            lbage.setText("");
            pswdretype.setText("");
            txtshow.setText("");
        }

    }//GEN-LAST:event_btnclearActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        if (id == -1) {
            Login mj = new Login();
            mj.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        Connection connect = DbConnection.getConnection();

        if (txtusername.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        } else if (pswdreg.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        } else if (txtfname.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        } else if (txtlname.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        } else if (cbgender.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please Select gender.");
        } else if (txtaddress.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        } else if (txtnumber.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        } else if (txtemail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        } else if (cbusertype.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        } else if (jDatebday.getDate().equals("")) {
            JOptionPane.showMessageDialog(null, "Please select birth date.");

        } else {
            try {
                String icon = btnsubmit.getIcon().toString();
                if (icon.equals("C:\\Users\\win10dell\\Desktop\\LMS Icon\\submit.png")) {

                    String sql = "insert into `tablelms` (`username`, `password`,`firstname`,`lastname`,`mid`,`gender`,`address`,`contact`, `email`,`usertype`, `bday`, `age`) values (?,?,?,?,?,?,?,?,?,?,?,?)";
                    Statement s = connect.createStatement();
                    ResultSet rs = s.executeQuery("SELECT * FROM tablelms WHERE username = '" + txtusername.getText() + "'");

                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Username already exists", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    pre = connect.prepareStatement(sql);
                    pre.setString(1, txtusername.getText());

                    if (pswdreg.getText().equals(pswdretype.getText())) {
                        pre.setString(2, pswdreg.getText());
                    } else {
                        JOptionPane.showMessageDialog(null, "Password unmatched.");
                        return;
                    }
                    pre.setString(3, txtfname.getText());
                    pre.setString(4, txtlname.getText());
                    pre.setString(5, txtmid.getText());
                    pre.setString(6, (String) cbgender.getSelectedItem());
                    pre.setString(7, txtaddress.getText());

                    if (txtshow.getText().isEmpty()) {
                        pre.setString(8, "+63" + txtnumber.getText());
                    } else {
                        JOptionPane.showMessageDialog(null, "Contact number must contain 10 Digits.");
                        return;
                    }

                    pre.setString(9, txtemail.getText());
                    pre.setString(10, (String) cbusertype.getSelectedItem());
                    pre.setString(11, ((JTextField) jDatebday.getDateEditor().getUiComponent()).getText());

                    if (Integer.parseInt(lbage.getText()) <= 10) {
                        JOptionPane.showMessageDialog(null, "Under Restricted Age");
                        return;
                    } else {
                        pre.setString(12, lbage.getText());

                    }
                    pre.execute();
                    JOptionPane.showMessageDialog(null, "Congratulations! New account created successfully.");

                    if (id == -1) {
                        Login mj = new Login();
                        mj.setVisible(true);
                    }
                    this.dispose();
                } else {
                    String sql = "UPDATE tablelms SET"
                            + " username = ?,"
                            + " password = ?,"
                            + " firstname = ?,"
                            + " lastname = ?,"
                            + " mid = ?,"
                            + " gender = ?,"
                            + " address = ?,"
                            + " contact = ?,"
                            + " email = ?,"
                            + " usertype = ?,"
                            + " bday = ?,"
                            + " age = ?"
                            + " WHERE UserID = ?";
                    
                    int updateConfirm = JOptionPane.showConfirmDialog(null, "Are sure to Change Account details?", "Update Account", JOptionPane.OK_CANCEL_OPTION);
                    
                    if(updateConfirm == 0){
                        pre = connect.prepareStatement(sql);
                    pre.setString(1, txtusername.getText());

                    if (pswdreg.getText().equals(pswdretype.getText())) {
                        pre.setString(2, pswdreg.getText());
                    } else {
                        JOptionPane.showMessageDialog(null, "Password unmatched.");
                        return;
                    }
                    pre.setString(3, txtfname.getText());
                    pre.setString(4, txtlname.getText());
                    pre.setString(5, txtmid.getText());
                    pre.setString(6, (String) cbgender.getSelectedItem());
                    pre.setString(7, txtaddress.getText());

                    if (txtshow.getText().isEmpty()) {
                        pre.setString(8, "+63" + txtnumber.getText());
                    } else {
                        JOptionPane.showMessageDialog(null, "Contact number must contain 10 Digits.");
                        return;
                    }

                    pre.setString(9, txtemail.getText());
                    pre.setString(10, (String) cbusertype.getSelectedItem());
                    pre.setString(11, ((JTextField) jDatebday.getDateEditor().getUiComponent()).getText());

                    if (Integer.parseInt(lbage.getText()) <= 10) {
                        JOptionPane.showMessageDialog(null, "Under Restricted Age");
                        return;
                    } else {
                        pre.setString(12, lbage.getText());

                    }
                    pre.setString(13, id + "");
                    pre.execute();
                    JOptionPane.showMessageDialog(null, "Account Updated Successfully.");

                    if (id == -1) {
                        Login mj = new Login();
                        mj.setVisible(true);
                    }
                    this.dispose();
                    }
                    
                }
            } catch (Exception b) {
                b.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (id == -1) {
            Login mj = new Login();
            mj.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnsubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseEntered
        btnsubmit.setBackground(java.awt.Color.BLUE);
    }//GEN-LAST:event_btnsubmitMouseEntered

    private void btnsubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseExited
        btnsubmit.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnsubmitMouseExited

    private void btnclearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseEntered
        btnclear.setBackground(java.awt.Color.RED);
    }//GEN-LAST:event_btnclearMouseEntered

    private void btnclearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseExited
        btnclear.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnclearMouseExited

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        btnback.setBackground(java.awt.Color.GREEN);
    }//GEN-LAST:event_btnbackMouseEntered

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        btnback.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnbackMouseExited

    private void txtnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumber1ActionPerformed

    private void jDatebdayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDatebdayPropertyChange
        String dateOfBirth = ((JTextField) jDatebday.getDateEditor().getUiComponent()).getText();

        if (!dateOfBirth.isEmpty()) {
            String dob[] = dateOfBirth.split("/");
            int year = Integer.parseInt(dob[0]);
            int month = Integer.parseInt(dob[1]);
            int day = Integer.parseInt(dob[2]);

            LocalDate selectedDate = LocalDate.of(year, month, day);
            LocalDate currentDate = LocalDate.now();

            int resultYear = Period.between(selectedDate, currentDate).getYears();
            lbage.setText(resultYear + "");
        }

    }//GEN-LAST:event_jDatebdayPropertyChange

    private void cbusertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbusertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbusertypeActionPerformed

    private void txtnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumberKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
            return;
        }
        if (!txtnumber.getText().isEmpty()) {
            if (txtnumber.getText().length() < 9) {
                txtshow.setText("Must contain 10 digit number.");
            } else {
                txtshow.setText("");
                if (txtnumber.getText().length() == 10) {
                    evt.consume();
                }
            }
        } else {
            txtshow.setText("Must contain 10 digit number.");
        }
    }//GEN-LAST:event_txtnumberKeyTyped

    private void pswdregPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pswdregPropertyChange

    }//GEN-LAST:event_pswdregPropertyChange

    private void pswdretypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdretypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdretypeActionPerformed

    private void btnclearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnclearFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearFocusGained

    private void txtmidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmidKeyTyped
        char c = evt.getKeyChar();
        String field = txtmid.getText();
        if (Character.isDigit(c)) {
            evt.consume();
        }
        if (!field.isEmpty() && field.length() == 1) {
            if (!(c == KeyEvent.VK_DELETE || c == KeyEvent.VK_BACK_SPACE)) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtmidKeyTyped

    private void txtnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumberKeyPressed

    }//GEN-LAST:event_txtnumberKeyPressed

    private void pswdregFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswdregFocusLost
        String pass = pswdreg.getText();
        String confirm = pswdretype.getText();

        if (!pass.equals(confirm)) {
            txtshowpas.setText("Passwords do not match");
        } else {
            txtshowpas.setText("");
        }
    }//GEN-LAST:event_pswdregFocusLost

    private void pswdretypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswdretypeFocusLost
        String pass = pswdreg.getText();
        String confirm = pswdretype.getText();

        if (!pass.equals(confirm)) {
            txtshowpas.setText("Passwords do not match");
        } else {
            txtshowpas.setText("");
        }
    }//GEN-LAST:event_pswdretypeFocusLost

    private void pswdretypeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswdretypeKeyTyped
        char c = evt.getKeyChar();

        String pass = pswdreg.getText();
        String confirm = pswdretype.getText() + c;

        if (!pass.equals(confirm)) {
            txtshowpas.setText("Passwords do not match");
        } else {
            txtshowpas.setText("");
        }
    }//GEN-LAST:event_pswdretypeKeyTyped

    private void pswdregKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswdregKeyTyped
        char c = evt.getKeyChar();

        String pass = pswdreg.getText() + c;
        String confirm = pswdretype.getText();

        if (!pass.equals(confirm)) {
            txtshowpas.setText("Passwords do not match");
        } else {
            txtshowpas.setText("");
        }
    }//GEN-LAST:event_pswdregKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cbusertype;
    private com.toedter.calendar.JDateChooser jDatebday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbage;
    private javax.swing.JPasswordField pswdreg;
    private javax.swing.JPasswordField pswdretype;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtnumber1;
    private javax.swing.JLabel txtshow;
    private javax.swing.JLabel txtshowpas;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
