
package library_system_project;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.Month;
import java.time.Period;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Regform extends javax.swing.JFrame {
    Connection connect;
    ResultSet ab;
    PreparedStatement pre;
    
    
   
    
    
    /**
     * Creates new form Regform
     */
    public Regform() {
        initComponents();
        icon();
        
    }
     private void icon(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("244650586_432577631535911_8014217671605978899_n.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnback = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        pswdretype = new javax.swing.JPasswordField();
        cbusertype = new javax.swing.JComboBox<>();
        cbgender = new javax.swing.JComboBox<>();
        txtemail = new javax.swing.JTextField();
        txtnumber1 = new javax.swing.JTextField();
        txtnumber = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        pswdreg = new javax.swing.JPasswordField();
        txtmid = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbage = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDatebday = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Library Management System/create_account/");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(50, 157, 156));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnback.setBackground(new java.awt.Color(255, 255, 255));
        btnback.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnback.setText("Back");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbackMouseExited(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 690, 90, -1));

        btnsubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnsubmit.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsubmitMouseExited(evt);
            }
        });
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 690, -1, -1));

        btnclear.setBackground(new java.awt.Color(255, 255, 255));
        btnclear.setFont(new java.awt.Font("Ink Free", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclearMouseExited(evt);
            }
        });
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 690, 90, -1));

        jLabel17.setBackground(new java.awt.Color(86, 197, 149));
        jLabel17.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Confirm Password:");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.setOpaque(true);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 140, -1));

        pswdretype.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        pswdretype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdretypeActionPerformed(evt);
            }
        });
        jPanel1.add(pswdretype, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 270, -1));

        cbusertype.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        cbusertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        cbusertype.setEnabled(false);
        cbusertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbusertypeActionPerformed(evt);
            }
        });
        jPanel1.add(cbusertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 630, 270, -1));

        cbgender.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        cbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Select gender)", "Female", "Male", "Prefer Not To Answer" }));
        jPanel1.add(cbgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 270, -1));

        txtemail.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 270, -1));

        txtnumber1.setEditable(false);
        txtnumber1.setBackground(new java.awt.Color(255, 255, 255));
        txtnumber1.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        txtnumber1.setText("+63");
        txtnumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumber1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtnumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 40, -1));

        txtnumber.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        txtnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberActionPerformed(evt);
            }
        });
        txtnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumberKeyTyped(evt);
            }
        });
        jPanel1.add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 230, -1));

        txtaddress.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 270, -1));

        pswdreg.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        pswdreg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pswdregPropertyChange(evt);
            }
        });
        jPanel1.add(pswdreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 270, -1));

        txtmid.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 50, -1));

        txtlname.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jPanel1.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 150, -1));

        txtfname.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 270, -1));

        txtusername.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 270, -1));

        jLabel22.setBackground(new java.awt.Color(32, 80, 114));
        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Contact and User Type");
        jLabel22.setOpaque(true);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 170, 20));

        jLabel21.setBackground(new java.awt.Color(32, 80, 114));
        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Personal Info");
        jLabel21.setOpaque(true);
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 130, 20));

        jLabel20.setBackground(new java.awt.Color(32, 80, 114));
        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Account Details:");
        jLabel20.setOpaque(true);
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 130, 20));

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 80, 114), 3));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 460, 140));

        lbage.setBackground(new java.awt.Color(255, 255, 255));
        lbage.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        lbage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbage.setOpaque(true);
        jPanel1.add(lbage, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 40, 20));

        jLabel15.setBackground(new java.awt.Color(86, 197, 149));
        jLabel15.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Age:");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 40, 20));

        jDatebday.setBackground(new java.awt.Color(255, 255, 255));
        jDatebday.setDateFormatString("yyyy/MM/dd");
        jDatebday.setFont(new java.awt.Font("Ink Free", 1, 12)); // NOI18N
        jDatebday.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDatebdayPropertyChange(evt);
            }
        });
        jPanel1.add(jDatebday, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 170, 20));

        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 80, 114), 3));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 460, 140));

        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 80, 114), 3));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 460, 220));

        jLabel14.setBackground(new java.awt.Color(86, 197, 149));
        jLabel14.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Birthday:");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 140, 20));

        jLabel12.setBackground(new java.awt.Color(86, 197, 149));
        jLabel12.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("User Type:");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 140, 20));

        jLabel11.setBackground(new java.awt.Color(86, 197, 149));
        jLabel11.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Email:");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setOpaque(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 140, 20));

        jLabel10.setBackground(new java.awt.Color(86, 197, 149));
        jLabel10.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Contact #:");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setOpaque(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 140, 20));

        jLabel9.setBackground(new java.awt.Color(86, 197, 149));
        jLabel9.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Address:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 140, 20));

        jLabel8.setBackground(new java.awt.Color(86, 197, 149));
        jLabel8.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gender:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 140, 20));

        jLabel7.setBackground(new java.awt.Color(86, 197, 149));
        jLabel7.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("M.I:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 50, 20));

        jLabel6.setBackground(new java.awt.Color(86, 197, 149));
        jLabel6.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Last Name:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 140, 20));

        jLabel5.setBackground(new java.awt.Color(86, 197, 149));
        jLabel5.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("First Name:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 140, 20));

        jLabel4.setBackground(new java.awt.Color(86, 197, 149));
        jLabel4.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Password:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 140, -1));

        jLabel3.setBackground(new java.awt.Color(86, 197, 149));
        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Username:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 140, 20));

        jLabel2.setBackground(new java.awt.Color(32, 80, 114));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CREATE ACCOUNT");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 500, 60));

        jLabel1.setBackground(new java.awt.Color(207, 244, 210));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 500, 730));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10dell\\Downloads\\244384172_293169668991008_7683881940037026863_n.png")); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(889, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
       txtusername.setText("");
       pswdreg.setText("");
       txtfname.setText("");
       txtlname.setText("");
       txtmid.setText("");
       cbgender.setSelectedIndex(0);
       txtaddress.setText("");
       txtnumber.setText("");
       txtemail.setText("");
       cbusertype.setSelectedIndex(0);
       jDatebday.setCalendar(null);
       lbage.setText("");
       pswdretype.setText("");
       
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
        Login mj = new Login();
        mj.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        Connection connect = DbConnection.getConnection();
        
        if (txtusername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        }else if(pswdreg.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        }else if(txtfname.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
        }else if(txtlname.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
    }    else if(cbgender.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
    }   else if(txtaddress.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
    }   else if(txtnumber.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
    }   else if(txtemail.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
    }   else if(cbusertype.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill up blank fields.");
    }   else if (jDatebday.getDate().equals("")){
            JOptionPane.showMessageDialog(null, "Please select birth date.");
            
    }
    
    else{
        
        
        try{
                String sql = "insert into `tablelms` (`username`, `password`,`firstname`,`lastname`,`mid`,`gender`,`address`,`contact`, `email`,`usertype`, `bday`, `age`) values (?,?,?,?,?,?,?,?,?,?,?,?)";
                pre = connect.prepareStatement(sql);
                pre.setString(1, txtusername.getText());
                
                if (pswdreg.getText().equals(pswdretype.getText())){
                    pre.setString(2, pswdreg.getText());
                }else{
                    JOptionPane.showMessageDialog(null, "Password unmatched.");
                    return;
                }
                pre.setString(3, txtfname.getText());
                pre.setString(4, txtlname.getText());
                pre.setString(5, txtmid.getText());
                pre.setString(6, (String) cbgender.getSelectedItem());
                pre.setString(7, txtaddress.getText());
                pre.setString(8, txtnumber.getText());
                pre.setString(9, txtemail.getText());
                pre.setString(10, (String) cbusertype.getSelectedItem());
                pre.setString(11, ((JTextField)jDatebday.getDateEditor().getUiComponent()).getText());
                
                if (Integer.parseInt(lbage.getText())<=10){
                    JOptionPane.showMessageDialog(null, "Under Restricted Age");
                }else{
                    
                    pre.setString(12, lbage.getText());
                    return;
                }
                
                
                pre.execute();
                
                JOptionPane.showMessageDialog(null, "Congratulations! New account created successfully.");
            }catch (Exception b){
                b.printStackTrace();
            }
    }                                            
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       new Login().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnsubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseEntered
        btnsubmit.setBackground(java.awt.Color.blue);
    }//GEN-LAST:event_btnsubmitMouseEntered

    private void btnsubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseExited
        btnsubmit.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnsubmitMouseExited

    private void btnclearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseEntered
       btnclear.setBackground(java.awt.Color.red);
    }//GEN-LAST:event_btnclearMouseEntered

    private void btnclearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseExited
        btnclear.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnclearMouseExited

    private void btnbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseEntered
        btnback.setBackground(java.awt.Color.green);
    }//GEN-LAST:event_btnbackMouseEntered

    private void btnbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseExited
        btnback.setBackground(java.awt.Color.white);
    }//GEN-LAST:event_btnbackMouseExited

    private void txtnumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumber1ActionPerformed

    private void jDatebdayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDatebdayPropertyChange
        String dateOfBirth = ((JTextField)jDatebday.getDateEditor().getUiComponent()).getText();
        
            if (!dateOfBirth.isEmpty()){
                String dob[] = dateOfBirth.split("/");
                int year = Integer.parseInt(dob[0]);
                int month = Integer.parseInt(dob[1]);
                int day = Integer.parseInt(dob[2]);
        
                LocalDate selectedDate = LocalDate.of(year, month, day);
                LocalDate currentDate = LocalDate.now();
        
                int resultYear = Period.between(selectedDate, currentDate).getYears();
                lbage.setText(resultYear + "");    
            }
        
    }//GEN-LAST:event_jDatebdayPropertyChange

    private void cbusertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbusertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbusertypeActionPerformed

    private void txtnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumberKeyTyped
       char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
        evt.consume();
        return;
        }
        if(!txtnumber.getText().isEmpty()&&txtnumber.getText().length()==10){
            evt.consume();
        }
    }//GEN-LAST:event_txtnumberKeyTyped

    private void pswdregPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pswdregPropertyChange
       
    }//GEN-LAST:event_pswdregPropertyChange

    private void pswdretypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdretypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdretypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JComboBox<String> cbgender;
    private javax.swing.JComboBox<String> cbusertype;
    private com.toedter.calendar.JDateChooser jDatebday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbage;
    private javax.swing.JPasswordField pswdreg;
    private javax.swing.JPasswordField pswdretype;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtnumber1;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
